spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: test
      password: test
      profile: development
zuul:
  routes:
    agency-service:
      path: /isu-app/**
      serviceId: isu-app
  okhttp:
    enabled: true
  ignoredServices: '*'
server:
  port: 8082
ribbon:
  eureka:
    enabled: true
  OkToRetryOnAllOperations: true