server:
  port: 8761

spring:
  application:
    name: api-gateway


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8760/eureka

zuul:
  routes:
    starship:
      path: /**
      service-id: starship-service
  okhttp:
    enabled: true

ribbon:
    eureka:
      enabled: true
    OkToRetryOnAllOperations: true
#  config:
#    import: configserver:http://localhost:8888
#  cloud:
#    config:
#      username: test
#      password: test
#      profile: development
