spring:
  application:
    name: starship-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: test
      password: test
      profile: development
server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password

