spring:
  application:
    name: starship-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      username: test
      password: test
      profile: development
server:
  port: 0

